### ISSUE TITLE
lpc81x / M0+ builds not working - Typo in lpc81x.S

### ISSUE THREAD

**Issue by ben-marshall** [danpage/scale-hw#1]
[Line 22](https://github.com/danpage/scale-hw/blob/fa15667bf32cdae6ed65c8f2c26735290ff85429/share/lpc81x/lpc81x.S#L22) of `/share/lpc81x/lpc81x.S` makes the wrong symbol name globally available.

It currently says `LPC81X_GPIO0`, but should say `LPC81X_GPIO` - i.e., there shouldn't be a trailing zero.

**Comment by danpage** [comment]
Great: thanks.  I'm collecting a bunch of fixes in the `fixes` branch, so have addressed it there and will merge into `master` once I'm done with the rest.
